apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: developer-portal
  definition:
    $text: 'https://github.com/OAI/OpenAPI-Specification/blob/main/tests/v3.0/pass/petstore.yaml'
